### ISSUE TITLE
Make task running parallelizable

### ISSUE THREAD

**Issue by rowanmanning** [pa11y/webservice#17]
This should be configurable, that way people who are paying for loads of RAM can run more tasks in parallel https://github.com/springernature/pa11y-webservice/blob/master/task/pa11y.js#L70

**Comment by rowanmanning** [comment]
I'm going to leave this open for now but document that it's unlikely to be added in by the core team. If you're interested in trying to do this then we're still happy to guide you a little.

**Comment by rowanmanning** [comment]
Going to close this as we're not prioritising feature work in Webservice. If somebody finds this and does the work, we'll probably still accept a PR.

**Comment by TathagataRoy1278** [comment]
Hello, is concurrency still an option youd like to add? If yes, could you please give some pointers(pun intended).
