### ISSUE TITLE
Add Route to retrieve Task IDs

### ISSUE THREAD

**Issue by RobLoach** [pa11y/webservice#19]
Have a new route that allows finding the TaskID of a given site title/name.....

GET
`/taskid/{siteName}`

**Comment by joseluisbolos** [comment]
Hi @RobLoach,

Thanks for creating this issue. In order to be able to assess the usefulness of this, would you be able to provide a use case for it, please?

Thanks.

**Comment by RobLoach** [comment]
Working on creating a small embeddable widget for people to display their accessibility report. Users will not be able to find the TaskID for their site. They'll instead be providing the Name or URL of the site.

Having a way to retrieve the task ID from the site name or URL will allow that to happen.

**Comment by rowanmanning** [comment]
Ah, possible solution: making the `/tasks` endpoint filterable with a `q` query parameter or something?

**Comment by rowanmanning** [comment]
Going to close this as we're not prioritising feature work in Webservice. If somebody finds this and does the work, we'll still accept a PR.
