### ISSUE TITLE
pa11y behind a proxy?

### ISSUE THREAD

**Issue by tassoman** [pa11y/webservice#3]
Well I'm trying pa11y dashboard and webservice but my virtualmachine is set behind a proxy. I've already set my ENV shell variables http_proxy but wasn't helpful.

As far I can see, I should invoke PhantomJS using _--proxy ip:port_ arguments. Any advice about bootstrapping pa11y-webservice with PhantomJS arguments?

**Comment by rowanmanning** [comment]
I'm going to close this for now as it's really old and the webservice/dashboard have changed quite a lot since. Also we're winding down feature work. If this is likely to be a useful feature for people then we could add to [Sidekick](https://github.com/pa11y/sidekick).
