### ISSUE TITLE
Automatically remove older results

### ISSUE THREAD

**Issue by DannyJoris** [pa11y/webservice#36]
If you have a large number of URLs that are audited daily, the database can get filled up really quickly. I searched in the code base and I don't think there's a mechanism in place that removes old results? For example all results older than 30 days.

**Comment by rowanmanning** [comment]
Hi Danny, currently there's nothing removed from the database but this would be a useful feature to add. We're currently ramping down feature development on Webservice and Dashboard in favour of [Sidekick](https://github.com/pa11y/sidekick), but I'd imagine this being very helpful.

If you or anyone else wants to PR something then we'd definitely accept it.

**Comment by ArdWang** [comment]
this is beatufiul

**Comment by rowanmanning** [comment]
Going to close this as we're not prioritising feature work in Webservice. If somebody finds this and does the work, we'll still accept a PR.
