### ISSUE TITLE
Error starting Pa11y Webservice

### ISSUE THREAD

**Issue by mgifford** [pa11y/webservice#37]
I don't understand why the Webservice uri is 0.0.0.0 or why the connection is refused to localhost.

Any thoughts on debugging this?

MacBook:pa11y-webservice $ PORT=8080 node index.js

Pa11y Webservice started
mode: development
uri:  http://0.0.0.0:3000

Error starting Pa11y Webservice:
connect ECONNREFUSED 127.0.0.1:27017

**Comment by hollsk** [comment]
Hey @mgifford - I'm going to close this as I see from your comment in https://github.com/pa11y/dashboard/issues/82 that you got there a couple of days later. Really sorry we didn't pick this up at the time!

**Comment by mgifford** [comment]
Thanks @hollsk - can't follow all the threads... :)
