### ISSUE TITLE
Website Logins

### ISSUE THREAD

**Issue by messyhead** [pa11y/webservice#40]
Hi. I'm new to using pa11y, and I have the webservice working locally. The site I'm testing has a login page to access any other URL.

Is there any way to add authentication when trying to reach URLs past the login form?

Is there also a way to pass a list of URLs to the service when the task is run?

**Comment by rowanmanning** [comment]
Hi @messyhead, you should be able to set the `username` and `password` properties when you create or edit a tasks. This will use basic auth. If you wish to use a custom login form then this currently isn't supported in the webservice.

I'm working on allowing setting of custom headers, which you could use to set an auth cookie. I'll let you know when this is working (should be later today).

**Comment by rowanmanning** [comment]
Hi again, I've added the ability to set headers in `2.1.1`, the documentation has been updated: https://github.com/pa11y/webservice/wiki/Web-Service-Endpoints

I'm not sure what you mean by:
> Is there also a way to pass a list of URLs to the service when the task is run?

**Comment by messyhead** [comment]
Thanks for the info on username/password.

For the URLs, I was thinking that you could somehow provide a list of the pages on a site that would all get assessed by a task, rather than have one URL per task.

**Comment by rowanmanning** [comment]
Ah that's a feature that's planned for Pa11y Sidekick (https://github.com/pa11y/sidekick/issues/10), it'd be a large rewrite of Webservice so it won't make it in I'm afraid
